Add test cases for required-optional.json
Azure/autorest.swift pull request #279
Opened 2020-11-29 06:53 UTC by sacheu

2020-11-30 20:37 UTC, tjprescott requested changes
One small nit.

2020-11-30 20:42 UTC, sacheu commented on AutorestSwiftTest/AutoRestRequiredOptionaltTest.swift
> +// --------------------------------------------------------------------------
Thanks. Push a new iteration with the fix

2020-12-03 18:49 UTC, tjprescott approved these changes

2020-12-03 19:20 UTC, tjprescott commented
One test is failing, which I commented out. I will address it on the `dev/AzureCore` branch.

2020-12-03 19:33 UTC, merged

2020-12-04 19:13 UTC, sacheu commented
Fix AB#2321068